import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Data from '../sections/Data'
import Heropage from '../sections/Heropage'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Pangkalan Data UMB</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <main className='px-4 md:px-8 xl:px-[5rem]'>
                <Heropage/>
                <Data/>
            </main>

            <Footer/>
        </div>
    )
}
